<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
                        <?php
                        //Fixed code By navin
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
                        $categoryId = $category->getId();
                        $active_range = "";
                        if ($categoryId == 3) {
                            $active_range = '0 1 2 4 5';
                        } else if ($categoryId == 5) {
                            $active_range = '0 1 3 4 5';
                        } else if ($categoryId == 8) {
                            $active_range = '0 1 3 4 5 6 7 8';
                        } else if ($categoryId == 13) {
                            $active_range = '0 1 3 4 5 6 7 8';
                        } else if ($categoryId == 19) {
                            $active_range = '0 1 2 4 5 6 7 8';
                        } else if ($categoryId == 20) {
                            $active_range = '0 1 2 4 5 6 7 8';
                        } else {
                            $active_range = '0 1 3 4 5 6 7 8';
                        }
                        //End Fixed code By navin
                        //this code for leave all open
                        //$range = implode(' ', range(0, $filter->getItemsCount()));
                        //$active_range = '0 1 2 4 5';
                        ?>

                        <?php ?>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active":  "<?php echo $active_range; ?>", "multipleCollapsible": true}}'>
                            <?php
                            $wrapOptions = true;
                        endif;
                        ?>
                        <div data-role="collapsible" class="filter-options-item">
                            <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
                            <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
